version: '3'

services:

##############################
#    Setup node container    #
##############################

    server:
        build: ./backend
        expose:
            - 8000
        environment:
            API_HOST: "http://0.0.0.0:3000/"
            APP_SERVER_PORT: 8000
        ports:
            - 8000:8000
        volumes:
            - ./backend/src:/srv/app/admin-server/src
        depends_on:
            - mongo    
        command: npm run start

##############################
#    Setup node container    #
##############################
    client:
        build: ./frontend
        environment:
            - REACT_APP_PORT=4000
        expose:
            - 4000    
        ports:
            - 4000:4000
        volumes:
            - ./frontend/src:/srv/app/admin-client/src
            - ./frontend/public:/srv/app/admin-client/public
        links:
            - server
        stdin_open: true
        command: npm run start

#####################
#   MONGO SERVICE   #  
#####################
    mongo:
        image: mongo
        ports:
            - "27017:27017"